apiConfiguration:
  apikeyParameter: apikey
  authDataSourceFactory:
    checkConnectionWhileIdle: false
    driverClass: org.hsqldb.jdbc.JDBCDriver
    maxSize: 32
    maxWaitForConnection: 1s
    minSize: 8
    password: password
    properties:
      charSet: UTF-8
    url: jdbc:hsqldb:res:/users/users
    user: SA
    validationQuery: /* MyService Health Check */ SELECT 1 FROM INFORMATION_SCHEMA.SYSTEM_USERS
  authenticationCachePolicy: maximumSize=10000, expireAfterAccess=10m
  authenticationQuery: select APIKEY from USERS where APIKEY = ?
  defaultApikey: default
  permissionQuery: select PERMISSION from ROLES where ROLE = ?
  roleQuery: select ROLES from USERS where APIKEY = ?
applicationContextPath: scigraph
cypherResources:
  - path: /dynamic/organParts/{id}
    query: |
            MATCH path = (start:Class{iri:'${id}'})-[:fma:regional_part|fma:constitutional_part|fma:related_part*0..40]->(part)-[:fma:arterial_supply|fma:nerve_supply*0..1]->(sup) RETURN path
    operations:
      - summary: Get the parts list for an organ including nervse and blood vessles
        parameters:
         - name: id
           descprtion: ontology id of the organ
           paramType: path
graphConfiguration:
  curies:
    ? ''
    : file:///ERROR/EMPTY/PREFIX/BANNED/
    BFO: http://purl.obolibrary.org/obo/BFO_
    BFO1: http://www.ifomis.org/bfo/1.1#
    BFO1SNAP: http://www.ifomis.org/bfo/1.1/snap#
    BFO1SPAN: http://www.ifomis.org/bfo/1.1/span#
    BIRNANN: http://ontology.neuinfo.org/NIF/Backend/BIRNLex_annotation_properties.owl#
    BIRNLEX: http://uri.neuinfo.org/nif/nifstd/birnlex_
    BIRNOBI: http://ontology.neuinfo.org/NIF/Backend/BIRNLex-OBI-proxy.owl#
    BIRNOBO: http://ontology.neuinfo.org/NIF/Backend/BIRNLex-OBO-UBO.owl#
    CAO: http://www.cognitiveatlas.org/ontology/cogat.owl#CAO_
    CHEBI: http://purl.obolibrary.org/obo/CHEBI_
    CL: http://purl.obolibrary.org/obo/CL_
    CLO: http://purl.obolibrary.org/obo/CLO_
    COGAT: http://www.cognitiveatlas.org/ontology/cogat.owl#
    COGPO: http://www.cogpo.org/ontologies/COGPO_
    COGPO1: http://www.cogpo.org/ontologies/CogPOver1.owl#COGPO_
    COGPO10: http://www.cogpo.org/ontologies/CogPOver2010.owl#COGPO_
    DICOM: http://uri.interlex.org/dicom/uris/terms/
    DOID: http://purl.obolibrary.org/obo/DOID_
    EFO: http://www.ebi.ac.uk/efo/EFO_
    ERO: http://purl.obolibrary.org/obo/ERO_
    FMA: http://purl.org/sig/ont/fma/fma
    fma: http://purl.org/sig/ont/fma/
    GBIF: http://www.gbif.org/species/
    GO: http://purl.obolibrary.org/obo/GO_
    HBA: http://api.brain-map.org:80/api/v2/data/Structure/
    HP: http://purl.obolibrary.org/obo/HP_
    IAO: http://purl.obolibrary.org/obo/IAO_
    ILX: http://uri.interlex.org/base/ilx_
    ILXREPLACE: http://ILXREPLACE.org/
    ITISTSN: http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=
    MA: http://purl.obolibrary.org/obo/MA_
    MBA: http://api.brain-map.org/api/v2/data/Structure/
    MESH: https://meshb.nlm.nih.gov/record/ui?ui=
    MP: http://purl.obolibrary.org/obo/MP_
    NCBIGene: http://www.ncbi.nlm.nih.gov/gene/
    NCBITaxon: http://purl.obolibrary.org/obo/NCBITaxon_
    NDA.CDE: http://uri.interlex.org/NDA/uris/datadictionary/elements/
    NIFANN: http://ontology.neuinfo.org/NIF/NIF-Annotation-Standard.owl#
    NIFCELL: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Cell.owl#
    NIFCHEM: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Chemical.owl#
    NIFDYS: http://ontology.neuinfo.org/NIF/Dysfunction/NIF-Dysfunction.owl#
    NIFEXT: http://uri.neuinfo.org/nif/nifstd/nifext_
    NIFFUN: http://ontology.neuinfo.org/NIF/Function/NIF-Function.owl#
    NIFGA: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-GrossAnatomy.owl#
    NIFGG: http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Government-Granting-Agency.owl#
    NIFINV: http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Investigation.owl#
    NIFMOL: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Molecule.owl#
    NIFMOLINF: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Molecule-Role-Inferred.owl#
    NIFMOLROLE: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Molecule-Role-Bridge#
    NIFNCBI: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-NCBITax-Bridge.owl#
    NIFNCBISLIM: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-NCBITaxonomy-Slim.owl#
    NIFNEURBR: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Neuron-BrainRegion-Bridge.owl#
    NIFNEURBR2: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Neuron-Brain-Bridge.owl#
    NIFNEURCIR: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Neuron-Circuit-Role-Bridge.owl#
    NIFNEURMC: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF_Neuron_MolecularConstituent_Bridge.owl#
    NIFNEURMOR: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Neuron-Morphology-Bridge.owl#
    NIFNEURNT: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Neuron-NT-Bridge.owl#
    NIFORG: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Organism.owl#
    NIFQUAL: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Quality.owl#
    NIFRES: http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Resource.owl#
    NIFRID: http://uri.neuinfo.org/nif/nifstd/readable/
    NIFSCID: http://ontology.neuinfo.org/NIF/DigitalEntities/NIF-Scientific-Discipline.owl#
    NIFSTD: http://uri.neuinfo.org/nif/nifstd/
    NIFSUB: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Subcellular.owl#
    NIFUNCL: http://ontology.neuinfo.org/NIF/BiomaterialEntities/NIF-Unclassified.owl#
    NLX: http://uri.neuinfo.org/nif/nifstd/nlx_
    NLXANAT: http://uri.neuinfo.org/nif/nifstd/nlx_anat_
    NLXBR: http://uri.neuinfo.org/nif/nifstd/nlx_br_
    NLXCELL: http://uri.neuinfo.org/nif/nifstd/nlx_cell_
    NLXCHEM: http://uri.neuinfo.org/nif/nifstd/nlx_chem_
    NLXDYS: http://uri.neuinfo.org/nif/nifstd/nlx_dys_
    NLXFUNC: http://uri.neuinfo.org/nif/nifstd/nlx_func_
    NLXINV: http://uri.neuinfo.org/nif/nifstd/nlx_inv_
    NLXMOL: http://uri.neuinfo.org/nif/nifstd/nlx_mol_
    NLXNEURNT: http://uri.neuinfo.org/nif/nifstd/nlx_neuron_nt_
    NLXOEN: http://uri.neuinfo.org/nif/nifstd/oen_
    NLXORG: http://uri.neuinfo.org/nif/nifstd/nlx_organ_
    NLXQUAL: http://uri.neuinfo.org/nif/nifstd/nlx_qual_
    NLXRES: http://uri.neuinfo.org/nif/nifstd/nlx_res_
    NLXSUB: http://uri.neuinfo.org/nif/nifstd/nlx_subcell_
    NLXUBO: http://uri.neuinfo.org/nif/nifstd/nlx_ubo_
    NLXUNCL: http://uri.neuinfo.org/nif/nifstd/nlx_uncl_
    OBI: http://purl.obolibrary.org/obo/OBI_
    OBOANN: http://ontology.neuinfo.org/NIF/Backend/OBO_annotation_properties.owl#
    PAR: http://uri.interlex.org/fakeobo/uris/obo/PAR_
    PATO: http://purl.obolibrary.org/obo/PATO_
    PAXRAT: http://uri.interlex.org/paxinos/uris/rat/labels/
    PR: http://purl.obolibrary.org/obo/PR_
    PW: http://purl.obolibrary.org/obo/PW_
    RO: http://purl.obolibrary.org/obo/RO_
    RadLex: http://www.radlex.org/RID/
    SAO: http://uri.neuinfo.org/nif/nifstd/sao
    SAOCORE: http://ontology.neuinfo.org/NIF/BiomaterialEntities/SAO-CORE_properties.owl#
    SBO: 'http://www.ebi.ac.uk/sbo/main/SBO:'
    SCR: http://scicrunch.org/resolver/SCR_
    SIO: http://semanticscience.org/resource/SIO_
    SO: http://purl.obolibrary.org/obo/SO_
    SWO: http://www.ebi.ac.uk/efo/swo/SWO_
    SWOL: http://www.ebi.ac.uk/swo/license/SWO_
    SYMP: http://purl.obolibrary.org/obo/SYMP_
    TRANS: http://purl.obolibrary.org/obo/TRANS_
    UBERON: http://purl.obolibrary.org/obo/UBERON_
    UO: http://purl.obolibrary.org/obo/UO_
    chebi: http://purl.obolibrary.org/obo/chebi/
    ilxtr: http://uri.interlex.org/tgbugs/uris/readable/
    obo: http://purl.obolibrary.org/obo/
    oboInOwl: http://www.geneontology.org/formats/oboInOwl#
  exactNodeProperties:
  - label
  - synonym
  - acronym
  - abbreviation
  indexedNodeProperties:
  - label
  - synonym
  - curie
  - acronym
  - abbreviation
  location: /var/lib/scigraph/sparc-graph
  neo4jConfig:
    dbms.pagecache.memory: 4g
    dump_configuration: true
logging:
  level: INFO
server:
  adminContextPath: /admin
  applicationContextPath: /scigraph
  connector:
    port: 9001
    type: http
  type: simple
serviceMetadata:
  identifierSpace: http://neuinfo.org/
  name: NIF Reconciliation Service
  preview:
    height: 400
    url: http://None:9001/scigraph/refine/preview/{id}
    width: 400
  schemaSpace: http://neuinfo.org/
  view:
    url: http://None:9001/scigraph/refine/view/{id}
